services:
  init:
    image: ${CUSTOM_IMAGE:-iq-release}:${CUSTOM_TAG:-latest}
    platform: linux/amd64
    env_file:
      - ./.env
    volumes:
      - sites:/home/{{ cookiecutter.image_user }}/bench/sites
      - ../scripts:/home/{{ cookiecutter.image_user }}/bench/bin-dev:ro
    entrypoint: /home/{{ cookiecutter.image_user }}/bench/bin-dev/init_site.sh
    depends_on:
      db:
        condition: service_started
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
