ARG BASE_IMAGE_SOURCE
ARG DEV_IMAGE_SOURCE

# Stage 1: Cleaning stage
FROM ${DEV_IMAGE_SOURCE:-iq-dev} AS cleaner

ARG IMAGE_USER={{ image_user }}
ARG IMAGE_GROUP={{ image_group }}

USER root

WORKDIR /home/${IMAGE_USER}/bench

# Run app-specific cleanup tasks defined in hooks
RUN PYTHON_PATH=/home/${IMAGE_USER}/bench/apps python apps/iq_core/delivery/resources/call_root_iq_release_dist.py

# Stage 2: Final stage with only cleaned files
FROM ${BASE_IMAGE_SOURCE:-iq-base} AS final

ARG IMAGE_USER={{ image_user }}
ARG IMAGE_GROUP={{ image_group }}

USER root

RUN find /home/${IMAGE_USER}/bench/sites_assets/ -type d -print0 | xargs -0 -r chmod 775 ; \
	find /home/${IMAGE_USER}/bench/sites_assets/ -type f -print0 | xargs -0 -r chmod 644 ;

RUN rm -rf /home/${IMAGE_USER}/.nvm/versions/node/v*/lib/node_modules/npm/node_modules/*; \
	rm -rf /home/${IMAGE_USER}/.nvm/versions/node/v*/lib/node_modules/npm; \
	rm -rf /home/${IMAGE_USER}/.nvm/versions/node/v*/lib/node_modules/corepack/shims/npm; \
	rm -rf /home/${IMAGE_USER}/.nvm/versions/node/v*/lib/node_modules/corepack/shims/*/npm; \
	rm -rf /home/${IMAGE_USER}/.nvm/versions/node/v*/bin/npm; \
	/usr/local/bin/pip uninstall -y pip

# Copy only the cleaned files from the cleaner stage
COPY --from=cleaner --chown=${IMAGE_USER}:${IMAGE_GROUP} /home/${IMAGE_USER}/bench /home/${IMAGE_USER}/bench
COPY --from=cleaner /usr/local/bin/psql /usr/local/bin/psql
COPY --from=cleaner /lib/x86_64-linux-gnu/libpq.so* /lib/x86_64-linux-gnu/
COPY --from=cleaner --chown=${IMAGE_USER}:${IMAGE_GROUP} /opt/nginx/ /opt/nginx/
COPY --from=cleaner --chown=${IMAGE_USER}:${IMAGE_GROUP} /opt/pcre2/* /opt/pcre2/

ENV PATH="/home/${IMAGE_USER}/bench/env/bin:${PATH}"

USER ${IMAGE_USER}

RUN chmod -R g+rw /home/${IMAGE_USER}/bench/config

WORKDIR /home/${IMAGE_USER}/bench

VOLUME [ \
	"/home/${IMAGE_USER}/bench/sites" \
	# "/home/${IMAGE_USER}/bench/sites/assets" \
	# "/home/${IMAGE_USER}/bench/logs" \
        ]

