web: bench serve --port 8000 1>> logs/web.log 2>> logs/web.error.log

socketio: node apps/frappe/socketio.js 1>> logs/socketio.log 2>> logs/socketio.error.log

watch: bench watch

schedule: bench schedule 1>> logs/schedule.log 2>> logs/schedule.error.log
worker:  bench worker 1>> logs/worker.log 2>> logs/worker.error.log
