# PostgreSQL database service
# Environment variables are provided via --env-file from stage configuration

services:
  db:
    image: postgres:16
    profiles:
      - db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-scram-sha-256}

volumes:
  pg_data:
