#!/usr/bin/env python3
"""
Generate Dockerfiles from templates after copier copy/update.

This script is called as a copier task to generate the initial Dockerfiles
from the docker-templates/*.j2 files using baker-cli.

During copier update, copier runs tasks in temporary directories for old-vs-new
comparison. The script detects this (no .git directory) and creates stable
placeholder files so copier's 3-way merge doesn't produce false diffs.

Usage (as copier task):
    python3 gen_dockerfiles.py <dst_path> [variant]
"""

import subprocess
import sys
from pathlib import Path

TARGETS = ["base", "builder", "dev", "release"]


def main():
    if len(sys.argv) < 2:
        print("[skip] gen_dockerfiles.py: No destination path provided")
        return

    dst_path = Path(sys.argv[1])
    cli_variant = sys.argv[2] if len(sys.argv) > 2 else None

    settings_file = dst_path / "ops" / "build" / "build-settings.yml"
    docker_dir = dst_path / "ops" / "build" / "docker"

    if not settings_file.exists():
        print(f"[skip] gen_dockerfiles.py: Settings file not found: {settings_file}")
        return

    # Detect copier's temp comparison directory (no .git = not a real project)
    is_temp_dir = not (dst_path / ".git").exists()

    if is_temp_dir:
        # In copier's temp dir: create stable placeholders so the old-vs-new
        # diff doesn't show Dockerfiles as added/deleted/changed.
        docker_dir.mkdir(parents=True, exist_ok=True)
        for target in TARGETS:
            placeholder = docker_dir / f"Dockerfile.{target}"
            if not placeholder.exists():
                placeholder.write_text(
                    f"# Dockerfile.{target} — generated by: ops dockerfile create\n"
                )
        print("[ok] gen_dockerfiles.py: placeholder files for copier diff")
        return

    # Real project directory — skip if Dockerfiles already exist
    existing_dockerfiles = list(docker_dir.glob("Dockerfile.*"))
    if existing_dockerfiles and "--force" not in sys.argv:
        print(f"[ok] Dockerfiles already exist in {docker_dir.name}/")
        print("     Run 'ops dockerfile update' to regenerate")
        return

    # Resolve variant: CLI arg > build-settings.yml > fallback
    variant = cli_variant or "debian"
    if not cli_variant:
        try:
            import yaml
            with open(settings_file) as f:
                settings = yaml.safe_load(f) or {}
            variant = settings.get("dockerfile_settings", {}).get("variant", "debian")
        except Exception:
            pass

    # Try to run baker gen-docker
    try:
        cmd = [
            sys.executable, "-m", "baker_cli", "gen-docker",
            "--settings", str(settings_file),
            "--variant", variant
        ]

        print(f"[task] Generating Dockerfiles (variant: {variant})...")
        result = subprocess.run(cmd, cwd=dst_path, capture_output=True, text=True)

        if result.returncode == 0:
            print(f"[ok] Generated Dockerfiles in {docker_dir.name}/")
        else:
            if "No module named 'baker_cli'" in result.stderr:
                print("[skip] baker-cli not installed yet")
                print("       Run 'ops dockerfile create' after installation")
            elif "No Dockerfile templates found" in result.stderr:
                print("[skip] No Dockerfile templates found yet")
                print("       Run 'ops dockerfile create' after copier update")
            else:
                print(f"[warn] gen_dockerfiles.py failed: {result.stderr.strip()}")

    except FileNotFoundError:
        print("[skip] Python/baker-cli not available")
        print("       Run 'ops dockerfile create' after setup")


if __name__ == "__main__":
    main()
